name: Wechat Linux Dest Version

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  save_new_wechat:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      # - name: Test Github Action Server Time
      #   run: echo `date`
      - name: Check new version and push
        env: 
          GHTOKEN: ${{ secrets.GHTOKEN }}
          GH_TOKEN: ${{ github.token }}
        run: bash -x ./scripts/destVersionRelease.sh ${{ github.event.inputs.download_link }}
